analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3321637,\\n  \\"name\\"\: \\"Rahul Project\\",\\n  \\"teamId\\"\: 3293649,\\n  \\"organizationId\\"\: 1263589,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3293649\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
